# Generated by Django 3.0.9 on 2020-08-05 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('address_line1', models.CharField(max_length=50, null=True)),
                ('address_line2', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('zipcode', models.IntegerField(null=True)),
                ('job_Title', models.CharField(max_length=50, null=True)),
                ('technology', models.CharField(max_length=50, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('contact', models.CharField(max_length=20, null=True, verbose_name='Consultant Phone')),
                ('email_id', models.EmailField(max_length=150, null=True, verbose_name='Consultant Email')),
                ('t_s_d', models.DateField(verbose_name='Training Start Date')),
                ('t_e_d', models.DateField(verbose_name='Training End Date')),
                ('status', models.CharField(choices=[('LEAD', 'Lead'), ('PROSPECT', 'Prospect'), ('IN TRAINING', 'In Training'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('INVALID', 'Invalid')], max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'TraineeInfo',
            },
        ),
        migrations.CreateModel(
            name='TraineeDash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Consultant Phone')),
                ('email_id', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Consultant Email')),
                ('technology', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('trainee', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainee.TraineeInfo')),
            ],
            options={
                'verbose_name_plural': 'TraineeDash',
            },
        ),
    ]
