# Generated by Django 3.0.9 on 2020-08-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0003_auto_20200806_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeinfo',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
