# Generated by Django 3.0.9 on 2020-08-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0004_auto_20200806_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeinfo',
            name='t_e_d',
            field=models.DateField(editable=False, null=True, verbose_name='Training End Date'),
        ),
        migrations.AlterField(
            model_name='traineeinfo',
            name='t_s_d',
            field=models.DateField(editable=False, null=True, verbose_name='Training Start Date'),
        ),
    ]
