# Generated by Django 3.0.9 on 2020-08-06 14:12

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0005_auto_20200806_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeinfo',
            name='contact',
            field=models.CharField(max_length=20, null=True, validators=[utils.validators.validate_phone_number], verbose_name='Consultant Phone'),
        ),
    ]
