# Generated by Django 3.0.9 on 2020-08-05 09:31

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('address_line1', models.CharField(max_length=50, null=True)),
                ('address_line2', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('zipcode', models.IntegerField(null=True)),
                ('job_Title', models.CharField(max_length=50, null=True)),
                ('technology', models.CharField(max_length=50, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('contact', models.CharField(max_length=30, null=True, validators=[utils.validators.validate_phone_number])),
                ('email_id', models.EmailField(max_length=150, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Trainer',
            },
        ),
    ]
