# Generated by Django 3.0.9 on 2020-08-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_trainer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='address_line2',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='rate',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
