# Generated by Django 3.0.9 on 2020-08-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0003_auto_20200806_1247'),
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='trainee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainee.TraineeInfo'),
        ),
        migrations.AlterField(
            model_name='financials',
            name='margin',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
